version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: PTW.Database
    ports:
        - 3307:3307
    volumes:
        - ./datafiles:/var/lib/mysql
        - ./PTW-API/SqlScripts:/docker-entrypoint-initdb.d
    environment:
       MYSQL_ROOT_PASSWORD: Root0+
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbpassword
       MYSQL_TCP_PORT: 3307 # Since 3306 is a default port for MySQL, and it could already be in usage
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
  ptw-api:
    depends_on:
        - db
    image: ${DOCKER_REGISTRY-}ptwapi
    container_name: PTW.Api
    build:
      context: .
      dockerfile: PTW-API/Dockerfile
    restart: always
  elasticsearch:
    container_name: PTW.ElasticSearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    ports: 
        - 9200:9200
    volumes:
        - esdata:/usr/share/elasticsearch/data
    environment:
        - xpack.monitoring.templates.enabled=true
        - xpack.watcher.enabled=false
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
        - discovery.type=single-node
        - xpack.security.enabled=false
    networks:
      - es-net
  kibana:
    container_name: PTW.Kibana
    image: docker.elastic.co/kibana/kibana:8.4.3
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch
    environment:
        - ELASTICSEARCH_HOSTS=http://PTW.ElasticSearch:9200
    networks:
      - es-net
volumes: 
  esdata:
    driver: local
networks:
  es-net:
    driver: bridge
  #seq:
  #  image: datalust/seq:latest
  #  ports:
  #    - 80:80
  #    - 5341:5341
  #  environment:
  #    ACCEPT_EULA: Y
