version: '3.4'

services:
  db:
    image: mysql:latest
    container_name: PTW.Database
    ports:
        - 3307:3307
    volumes:
        - ./datafiles:/var/lib/mysql
        - ./SqlScripts/setup.ddl:/docker-entrypoint-initdb.d
    environment:
       MYSQL_ROOT_PASSWORD: Root0+
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbpassword
       MYSQL_TCP_PORT: 3307 # Since 3306 is a default port for MySQL, and it could already be in usage
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
  ptw-api:
    depends_on:
        - db
    image: ${DOCKER_REGISTRY-}ptwapi
    container_name: PTW.Api
    build:
      context: .
      dockerfile: PTW-API/Dockerfile
    restart: always
  #seq:
  #  image: datalust/seq:latest
  #  ports:
  #    - 80:80
  #    - 5341:5341
  #  environment:
  #    ACCEPT_EULA: Y
